#!/bin/bash
set -e

source debian/tests/launch-mm.sh

# stop ModemManager and make sure it's inactive
systemctl stop ModemManager.service
[[ $(systemctl is-active ModemManager.service) == "inactive" ]] || exit 1

# Patch some tests to use the installed ModemManager.service
patch -p1 < debian/tests/0001-Test-running-service-in-plugin-generic.patch
meson setup debian/build
meson test -C debian/build

# make sure ModemManager got dbus-activated by the unit-tests
[[ $(systemctl is-active ModemManager.service) == "active" ]] || exit 1
